// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/conversation.proto

package conversationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single chunk of a live conversation (chat or voice transcript).
type ConversationChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique session identifier (conversation id).
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Unique id of this message/chunk within the session.
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Who sent this chunk: e.g. "AGENT", "CUSTOMER", "SYSTEM".
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// The textual content (raw transcript or chat message).
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Event timestamp in milliseconds since epoch.
	TimestampMs int64 `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Extra metadata fields (channel, language, tags, etc.).
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationChunk) Reset() {
	*x = ConversationChunk{}
	mi := &file_proto_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationChunk) ProtoMessage() {}

func (x *ConversationChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationChunk.ProtoReflect.Descriptor instead.
func (*ConversationChunk) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConversationChunk) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ConversationChunk) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ConversationChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConversationChunk) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ConversationChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Acknowledgement from analytics/escalation engine after stream finishes.
type AnalyticsAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session this ACK corresponds to.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The last message_id successfully processed for this session.
	LastMessageId string `protobuf:"bytes,2,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	// Whether processing succeeded end-to-end.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Optional human-readable message (error, debug info, etc.).
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsAck) Reset() {
	*x = AnalyticsAck{}
	mi := &file_proto_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsAck) ProtoMessage() {}

func (x *AnalyticsAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsAck.ProtoReflect.Descriptor instead.
func (*AnalyticsAck) Descriptor() ([]byte, []int) {
	return file_proto_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticsAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalyticsAck) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *AnalyticsAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyticsAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_conversation_proto protoreflect.FileDescriptor

const file_proto_conversation_proto_rawDesc = "" +
	"\n" +
	"\x18proto/conversation.proto\x12\x0fconversation.v1\"\xab\x02\n" +
	"\x11ConversationChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.conversation.v1.ConversationChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\fAnalyticsAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\x0flast_message_id\x18\x02 \x01(\tR\rlastMessageId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2o\n" +
	"\x12ConversationStream\x12Y\n" +
	"\x12StreamConversation\x12\".conversation.v1.ConversationChunk\x1a\x1d.conversation.v1.AnalyticsAck(\x01B_Z]github.com/kaphack/lowlatency-realtime-conversation-ai-escalation-system/proto;conversationv1b\x06proto3"

var (
	file_proto_conversation_proto_rawDescOnce sync.Once
	file_proto_conversation_proto_rawDescData []byte
)

func file_proto_conversation_proto_rawDescGZIP() []byte {
	file_proto_conversation_proto_rawDescOnce.Do(func() {
		file_proto_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_conversation_proto_rawDesc), len(file_proto_conversation_proto_rawDesc)))
	})
	return file_proto_conversation_proto_rawDescData
}

var file_proto_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_conversation_proto_goTypes = []any{
	(*ConversationChunk)(nil), // 0: conversation.v1.ConversationChunk
	(*AnalyticsAck)(nil),      // 1: conversation.v1.AnalyticsAck
	nil,                       // 2: conversation.v1.ConversationChunk.MetadataEntry
}
var file_proto_conversation_proto_depIdxs = []int32{
	2, // 0: conversation.v1.ConversationChunk.metadata:type_name -> conversation.v1.ConversationChunk.MetadataEntry
	0, // 1: conversation.v1.ConversationStream.StreamConversation:input_type -> conversation.v1.ConversationChunk
	1, // 2: conversation.v1.ConversationStream.StreamConversation:output_type -> conversation.v1.AnalyticsAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_conversation_proto_init() }
func file_proto_conversation_proto_init() {
	if File_proto_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_conversation_proto_rawDesc), len(file_proto_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_conversation_proto_goTypes,
		DependencyIndexes: file_proto_conversation_proto_depIdxs,
		MessageInfos:      file_proto_conversation_proto_msgTypes,
	}.Build()
	File_proto_conversation_proto = out.File
	file_proto_conversation_proto_goTypes = nil
	file_proto_conversation_proto_depIdxs = nil
}
