// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/conversation.proto

package conversationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConversationStream_StreamConversation_FullMethodName = "/conversation.v1.ConversationStream/StreamConversation"
)

// ConversationStreamClient is the client API for ConversationStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for client-streaming conversation chunks.
type ConversationStreamClient interface {
	// Client opens a stream, sends multiple ConversationChunk messages,
	// server processes them in real-time and responds with a single ACK
	// when the client closes the stream.
	StreamConversation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ConversationChunk, AnalyticsAck], error)
}

type conversationStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationStreamClient(cc grpc.ClientConnInterface) ConversationStreamClient {
	return &conversationStreamClient{cc}
}

func (c *conversationStreamClient) StreamConversation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ConversationChunk, AnalyticsAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConversationStream_ServiceDesc.Streams[0], ConversationStream_StreamConversation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConversationChunk, AnalyticsAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConversationStream_StreamConversationClient = grpc.ClientStreamingClient[ConversationChunk, AnalyticsAck]

// ConversationStreamServer is the server API for ConversationStream service.
// All implementations must embed UnimplementedConversationStreamServer
// for forward compatibility.
//
// gRPC service for client-streaming conversation chunks.
type ConversationStreamServer interface {
	// Client opens a stream, sends multiple ConversationChunk messages,
	// server processes them in real-time and responds with a single ACK
	// when the client closes the stream.
	StreamConversation(grpc.ClientStreamingServer[ConversationChunk, AnalyticsAck]) error
	mustEmbedUnimplementedConversationStreamServer()
}

// UnimplementedConversationStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationStreamServer struct{}

func (UnimplementedConversationStreamServer) StreamConversation(grpc.ClientStreamingServer[ConversationChunk, AnalyticsAck]) error {
	return status.Error(codes.Unimplemented, "method StreamConversation not implemented")
}
func (UnimplementedConversationStreamServer) mustEmbedUnimplementedConversationStreamServer() {}
func (UnimplementedConversationStreamServer) testEmbeddedByValue()                            {}

// UnsafeConversationStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationStreamServer will
// result in compilation errors.
type UnsafeConversationStreamServer interface {
	mustEmbedUnimplementedConversationStreamServer()
}

func RegisterConversationStreamServer(s grpc.ServiceRegistrar, srv ConversationStreamServer) {
	// If the following call panics, it indicates UnimplementedConversationStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationStream_ServiceDesc, srv)
}

func _ConversationStream_StreamConversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConversationStreamServer).StreamConversation(&grpc.GenericServerStream[ConversationChunk, AnalyticsAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConversationStream_StreamConversationServer = grpc.ClientStreamingServer[ConversationChunk, AnalyticsAck]

// ConversationStream_ServiceDesc is the grpc.ServiceDesc for ConversationStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conversation.v1.ConversationStream",
	HandlerType: (*ConversationStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConversation",
			Handler:       _ConversationStream_StreamConversation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/conversation.proto",
}
